get_gaze_data_url="/v0/gaze/<sdk_id_str>"
get_fixation_data_url="/v0/fixations/<sdk_id_str>"
get_event_data_url="/v0/events/<sdk_id_str>"
get_dynamicobj_data_url="/v0/dynamics/<sdk_id_str>"
get_sensor_data_url="/v0/sensor/<sdk_id_str>"